### ISSUE TITLE
code tag styles overrides osu!wiki's initial ones

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-web#1104]
There is a style in `base.less` (line 51) that overrides the original styles for code tags in the osu!wiki:
```less
code {
  padding: 0;
  font-size: inherit;
  color: inherit;
  background: none;
  border-radius: 0;
}
```
Was this intended? This makes it a bit harder to differentiate between normal text and code since the only difference is the monospace font.
