### ISSUE TITLE
design tweek suggestion for banner shadow/glow

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#11816]
before  =>  after

https://github.com/user-attachments/assets/4c1ae6de-4323-4301-b4d4-efc13a4a8d66

css:
```css
.menu-images::before, .menu-images::after {
	pointer-events: none;
	content: '';
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	background: black;
	z-index: 1;
}

.menu-images__indicators {
	z-index: 2;
}


.menu-images::before {
	mask-image: linear-gradient(0deg, black -100%, transparent 40%);

}

.menu-images::after {
	mask-image: linear-gradient(180deg, black -100%, transparent 40%);
}

.menu-images {
	overflow: hidden;
}

.menu-images__blur:before {
	opacity: 0.6;
}
```
