### ISSUE TITLE
text in textarea inside discussion-new__message gets cut off

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#2088]
!["cutoff"](https://cdn.discordapp.com/attachments/318028997969838080/394156012707250176/unknown.png)

!["ex2](https://puu.sh/yMtax/875d4fa43f.png)

The textarea inside the newmessage box gets cut off by the new message box pretty hard. 
If you just want to quickly fix this, adding min-height to the new__message container would probably work:
```css
.beatmap-discussion-new__message {
min-height: 60px;
}
```
Otherwise i'd imagine you want it to fit the textarea's contents as people write stuff?
