### ISSUE TITLE
badly visible diff icon

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#5725]
.beatmap-icon--expert-plus
![chrome_vYnDrMwqFs](https://user-images.githubusercontent.com/21735205/76098529-37c0c900-5ffc-11ea-80d6-bc166b63cce7.png)

**Comment by peppy** [comment]
Could you please provide a link?

**Comment by cyperdark** [comment]
https://osu.ppy.sh/beatmapsets/774594#osu/1628000

**Comment by cyperdark** [comment]
reopened because it's still badly visible on maps above 8*
![1692863001_Ttu2wYnZyE](https://github.com/ppy/osu-web/assets/21735205/3832c7c3-fd12-409b-8378-75dca16ea2bf)


## as suggestion i have this: 
![1692863037_DM38CXkXEc](https://github.com/ppy/osu-web/assets/21735205/8ef2f0c6-edc2-4621-9e10-229382da2435)
![1692863124_9Oqf5Ctcla](https://github.com/ppy/osu-web/assets/21735205/91b9a4da-6412-4bbc-936a-1f75c906a631)

```css
.beatmapset-beatmap-picker__beatmap--active .beatmap-icon--beatmapset {
    color: hsl(0deg 0% 100% / 50%); /* slightly brigther version of the difficulty color*/
    z-index: 2;
}

.beatmapset-beatmap-picker__beatmap--active:before {
    border-color: rgb(220, 72, 163); /* instead color of the difficulty */
    background: black;
    z-index: 0;
}

.beatmapset-beatmap-picker__beatmap--active:after {
    content:'';
    position: absolute;
    top: 1px;
    left: 1px;
    width: calc(100% - 2px);
    height: calc(100% - 2px);
    background: rgba(220, 72, 163, 0.6);
    border-radius: 10px;
    z-index: 1;
}
```
