### ISSUE TITLE
add basic infobox support for wiki

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#7031]
the lack of infoboxes makes writing a lot of articles more difficult compared to mediawiki when you want to provide key points & a visual summary without disrupting the flow of the page. in lieu of having a more robust system to parse and render templates, I think it'd be nice to add styling for infoboxes so they can be included as normal markdown wrapped in an extra div. this implies allowing html in wiki page markdown, not sure if u want to do that

example on a nonsense page:

```markdown
<div class="osu-md__infobox">

#### Heading

![](https://a.ppy.sh/6616586?1434426025.png "Someone's avatar")

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

##### Smaller heading

| | |
| :-- | :-- |
| Property | It's a cat |
| Color | Blue and also here is more text sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium |
| More prop | ... |

</div>
```

```css
.osu-md__infobox {
  width: 300px;
  padding: 10px;
  margin-left: 10px;
  float: right;
  border: 1px solid hsl(var(--hsl-b4));
  text-align: center;
}

.osu-md__infobox > :last-child {
  margin-bottom: 0;
}

.osu-md__infobox thead {
  display: none;
}

.osu-md__infobox tbody > tr:first-child > td {
  border-top: none;
}

.osu-md__infobox td {
  vertical-align: top;
}
```

![image](https://user-images.githubusercontent.com/9954349/103279527-dac74280-4982-11eb-9376-ac4ab736d308.png)
