### ISSUE TITLE
Restricted account header color does not become red

### ISSUE THREAD

**Issue by MaxTechnics** [ppy/osu-web#8058]
When an account is restricted, the header does not become red. Which looks off

Expected:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/58440941/131016015-c7235621-deee-4d7c-9010-22682c29c5d8.png">

Expected result gotten by commenting out 2 css rules:

```css
.nav2-header--restricted .nav2-header__triangles {
	/* background-image: url(/assets/images/red@2x.2e2f51ea.png); */
}

.nav2-header__triangles {
	position: absolute;
	left: 0;
	top: 0;
	height: 100%;
	width: 100%;
	background-image: url(/assets/images/nav2-background-hue0.1aba1596.png);
	background-position: bottom center;
	background-repeat: repeat-x;
	/* filter: hue-rotate(var(--base-hue-deg)) saturate(0.6); */
}
```

Actual: 
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/58440941/131015609-17bf4a41-6c70-489e-a06f-d93e9b9c881d.png">

I'm taking a closer look tomorrow and might PR a fix
