### ISSUE TITLE
Better style for bbcode images

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#8600]
## Current styles
div.proportional-container__height
```css
element.style {
    padding-bottom: 20.909090909091%;
}

.proportional-container__height {
    display: block;
    position: relative;
}
```
img.proportional-container__content
```css
.proportional-container__content {
    position: absolute;
    height: 100%;
    width: 100%;
    top: 0;
    left: 0;
}
```
## New styles
div.proportional-container__height
```css
element.style {
    // remove this thing in div style
    padding-bottom: 20.909090909091%;
}

.proportional-container__height {
    display: flex;
}
```

#### img.proportional-container__content
```css
.proportional-container__content {}
```

# Tests
### Old 
![image](https://user-images.githubusercontent.com/21735205/152678721-97ce698a-f7ac-4fee-88de-ef95f503f2f7.png)
### New
![image](https://user-images.githubusercontent.com/21735205/152678778-6f46c45a-e9b5-462d-81d6-6e91a2b9eeaf.png)

### Old
![image](https://user-images.githubusercontent.com/21735205/152678801-6e36a8ab-67ed-420b-a2f1-dd20631242f0.png)
### New
![image](https://user-images.githubusercontent.com/21735205/152678840-21152187-604e-41a1-9fb1-07861903c505.png)

### **Also will be cool to have a note about min height of image (22px) in "me!" editor because i waste an hour to fix this lines**
![image](https://cdn.discordapp.com/attachments/592723349814378507/939835151310000208/unknown.png)
