### ISSUE TITLE
User profile design (elements position) suggestion

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#8691]
## Current
![chrome_ftfKhoFZpx](https://user-images.githubusercontent.com/21735205/156524567-3daa4e03-3215-404b-a2a4-396e8ffb644f.jpg)

## Suggestion
![chrome_014modXknQ](https://user-images.githubusercontent.com/21735205/156524677-c6e1d355-5b3d-4155-add5-5cae5c997f1e.jpg)

<details>
<summary>css style that i used to change user profile</summary>
<br>

```css

.profile-info__title {
	text-shadow: 0px 1px 1px black, 0px 1px 2px black;
	filter: brightness(2) saturate(0.5);
}

.profile-info__flag-flag {
	font-size: calc(var(--icon-height) / 1.2);
}

.profile-info__flags {
	margin-top: 5px;
}

.profile-info__flag-text {
	padding-left: 6px;
}

.profile-detail__stats {
	justify-content: center;
	align-items: center;
}

.bar--user-profile {
	height: 22px;
	overflow: hidden;
}

.bar__text {
	top: 50%;
	right: 10px;
	transform: translate(0, -50%);
	margin-top: 0;
}

.profile-info__bg::before {
	content: '';
	position: absolute;
	top: 0px;
	left: 0px;
	right: 0px;
	bottom: 0px;
	background: linear-gradient(0deg, rgba(0, 0, 0, 0.2) 0%, transparent 5%, transparent 95%, rgba(0, 0, 0, 0.2));
}

.profile-info__avatar {
	border-radius: calc(var(--cover-radius) / 1.5);
}

.profile-detail {
	position: relative;
	grid-template-areas: "stats" "badges";
}

.profile-detail .profile-badges {grid-area: badges;}
.profile-detail .profile-detail__stats {grid-area: stats;}
	
.profile-detail__stats>div:nth-child(1) {
	display: grid;
	grid-template-areas: "stats" "rank" "ranks";
}

.profile-detail__stats>div:nth-child(1)>div:nth-child(1) {grid-area: ranks;position: absolute;top: 0;right: 0;transform: translate(-40%, -145%);}
.profile-detail__stats>div:nth-child(1)>div:nth-child(2) {grid-area: rank;}
.profile-detail__stats>div:nth-child(1)>div:nth-child(3) {grid-area: stats;}
	
.profile-detail__stats>div:nth-child(1)>div:nth-child(3)>div:nth-child(1) {
	display: grid; 
	gap: 0px 30px; 
	grid-template-areas: "time medals pp"; 
}

.profile-detail__stats>div:nth-child(1)>div:nth-child(3)>div:nth-child(1)>div:nth-child(1) {grid-area: medals;min-width: fit-content;}
.profile-detail__stats>div:nth-child(1)>div:nth-child(3)>div:nth-child(1)>div:nth-child(2) {grid-area: pp;min-width: fit-content;}
.profile-detail__stats>div:nth-child(1)>div:nth-child(3)>div:nth-child(1)>div:nth-child(3) {grid-area: time;min-width: fit-content;}
	
.profile-info__icon--supporter {
	color: hsl(main_color,20%,25%);
}

.profile-badges {
	padding: 15px;
	overflow-y: auto;
	flex-wrap: nowrap;
	if enable_colors {
		background: hsl(main_color,10%,20%);
	} else {
		background: hsl(333,10%,20%);
	}
	border-radius: 4px;
	box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25);
}
```

</details>
